# Summa docs: Material + MkDocs, an excellent static site generator geared towards project documentation.
# It is built using Google's Material Design guidelines

#--------------------------------
#  PROJECT CUSTOM CONFIGURATION
#--------------------------------

# Project information
site_name: Warp Framework
site_description: Speeding up! your development infraestructure
site_author: Summa Solutions
site_url: http://docs.summasolutions.com.ar/

repo_name: 'summasolutions/summa-mkdocs'
repo_url: 'https://bitbucket.org/summasolutions/warp-engine/'
edit_uri: 'src/master/docs'

# Main menu
nav:
  - Introduction: index.md
  - Workshop video: 'workshop/workshop.md'
  - Get Started:
    - Requirements: 'started/requirements.md'
    - Usage: 'started/usage.md'
  - Installation:
    - MacOS: 'installation/mac.md'
    - Linux: 'installation/linux.md'
  - Features:
    - Services: 'features/services.md'
    - Magento: 'features/magento.md'
    - Oro: 'features/oro.md'
  - FAQs: 'faq/index.md'
  - Troubleshooting: 'troubleshooting/index.md'

use_directory_urls: false

# Uncomment next line to change default (docs) documentation folder
#docs_dir: summadocs

# Uncomment next line to disable "search" plugin
#plugins: []

#-------------------------------
# SITE AND THEME CONFIGURATIONS
#-------------------------------

# Copyright
copyright: 'Copyright &copy; 2019 Summa Solutions'

theme:
  name: material
  logo: 'img/summa_white.png'
  favicon: 'img/favicon.ico'
  palette:
    primary: 'light green'
    accent: 'green'
  font:
    text: 'Ubuntu'
    code: 'Ubuntu Mono'
  feature:
    tabs: false

extra_css:
  - 'css/extra.css'

extra:
  social:
    - type: 'globe'
      link: 'https://www.summasolutions.net'


# Extensions
markdown_extensions:
  - admonition
  - codehilite:
        linenums: true


