config:
  application: warp-engine
  repository: "git@github.com:Best-Worlds/warp-engine.git"
  http_user: false
  after:
    deploy:failed: deploy:unlock

hosts:
  satis:
    labels:
      stage: satis
    branch: master
    deploy_path: /var/www/html/warp-engine
    remote_user: root
    hostname: 192.241.202.17
    identity_file: /var/lib/jenkins/bww_dev.pem
    http_user: root
    http_group: root
    is_production: 1